# Generated by Django 3.1.7 on 2021-03-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('upload', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
