# Generated by Django 3.1.7 on 2021-03-22 07:42

import Frontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_auto_20210320_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to=Frontend.models.upload_path),
        ),
    ]
