# Generated by Django 3.1.7 on 2021-03-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_auto_20210322_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='driveLink',
            field=models.URLField(default=2, max_length=400),
            preserve_default=False,
        ),
    ]
