# Generated by Django 3.1.7 on 2021-03-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_auto_20210322_2349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload',
        ),
    ]
