# Generated by Django 3.1.7 on 2021-05-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_delete_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('phonenumber', models.IntegerField()),
                ('location', models.CharField(max_length=300)),
                ('stage', models.CharField(choices=[('1', 'none'), ('2', 'Pre-Idea Stage'), ('3', 'Idea Stage'), ('4', 'Prototyping Stage'), ('5', 'MVP/Early Market')], max_length=1)),
                ('industry', models.CharField(choices=[('1', 'none'), ('2', 'Information Technology'), ('3', 'Tourism'), ('4', 'E-commerce'), ('5', 'Education'), ('6', 'Services'), ('7', 'Textiles'), ('8', 'others')], max_length=1)),
                ('role', models.CharField(choices=[('1', 'none'), ('2', 'Founder'), ('3', 'Team Leader'), ('4', 'Investor'), ('5', 'Mentor'), ('6', 'other')], max_length=1)),
                ('members', models.CharField(choices=[('1', 'none'), ('2', 'Just me'), ('3', '2 to 5 people'), ('4', 'more than 5')], max_length=1)),
                ('idea', models.TextField()),
            ],
        ),
    ]
