# Generated by Django 3.1.7 on 2021-05-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0007_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='idea',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='fund',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
