# Generated by Django 3.1.7 on 2021-05-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0008_auto_20210508_1249'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fund',
            table='Fund',
        ),
    ]
