# Generated by Django 3.1.7 on 2021-05-08 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0009_auto_20210508_1310'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fund',
            table='Frontend_Fund',
        ),
    ]
