# Generated by Django 3.1.7 on 2021-05-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0010_auto_20210508_1312'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fund',
            table=None,
        ),
    ]
