# Generated by Django 3.1.7 on 2021-05-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0011_auto_20210508_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='industry',
            field=models.CharField(choices=[('none', 'Select'), ('Information Technology', 'Information Technology'), ('Tourism', 'Tourism'), ('E-commerce', 'E-commerce'), ('Education', 'Education'), ('Services', 'Services'), ('Textiles', 'Textiles'), ('others', 'others')], default='none', max_length=40),
        ),
        migrations.AlterField(
            model_name='fund',
            name='members',
            field=models.CharField(choices=[('none', 'Select'), ('Just me', 'Just me'), ('2 to 5 people', '2 to 5 people'), ('more than 5', 'more than 5')], default='none', max_length=40),
        ),
        migrations.AlterField(
            model_name='fund',
            name='role',
            field=models.CharField(choices=[('none', 'Select'), ('Founder', 'Founder'), ('Team Leader', 'Team Leader'), ('Investor', 'Investor'), ('Mentor', 'Mentor'), ('other', 'other')], default='none', max_length=40),
        ),
        migrations.AlterField(
            model_name='fund',
            name='stage',
            field=models.CharField(choices=[('none', 'Select'), ('Pre-Idea Stage', 'Pre-Idea Stage'), ('Idea Stage', 'Idea Stage'), ('Prototyping Stage', 'Prototyping Stage'), ('MVP/Early Market', 'MVP/Early Market')], default='none', max_length=40),
        ),
    ]
