# Generated by Django 3.1.7 on 2021-05-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0012_auto_20210508_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posttitle', models.CharField(max_length=100)),
                ('box1', models.BooleanField(default=False, verbose_name='Violent content')),
                ('box2', models.BooleanField(default=False, verbose_name='Abusive conten')),
                ('box3', models.BooleanField(default=False, verbose_name='Harmful content')),
                ('box4', models.BooleanField(default=False, verbose_name='Spam')),
                ('box5', models.BooleanField(default=False, verbose_name='Nudity')),
                ('details', models.TextField(max_length=300)),
            ],
        ),
    ]
