# Generated by Django 3.1.7 on 2021-05-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0013_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.BooleanField(default=False, verbose_name='Comments')),
                ('suggestions', models.BooleanField(default=False, verbose_name='Suggestions')),
                ('questions', models.BooleanField(default=False, verbose_name='Questions')),
                ('rate', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1)),
                ('remarks', models.TextField(max_length=300)),
            ],
        ),
    ]
