# Generated by Django 3.1.7 on 2021-05-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0014_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=300)),
            ],
        ),
    ]
