# Generated by Django 3.1.7 on 2021-05-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0015_contactu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactu',
            new_name='Contactus',
        ),
    ]
